In [1]:
# Dependencies
import pandas as pd
import numpy as np
import yfinance as yf
import datetime as dt

# Stock Grabber Function

In [4]:
# Function to grab data from yfinance
def stock_grabber(symbols, start_date_list, end_date_list = []):
    """
    Pulls financial data between start and end dates for specify stock.

    Params:
        symbols         : list of stock symbols to create csv files.
        start_date_list : start date in list form (i.e. [<year>, <month>, <day>]).
        end_date_list   : end date in list form (i.e. [<year>, <month>, <day>]).  It does not include the end dates.

    Returns:
        Saves csv files of desired stock into resource folder
    """

    start = dt.date(start_date_list[0], start_date_list[1], start_date_list[2])
    
    if end_date_list == []:
        end = dt.date.today()
    else:
        end = dt.date(end_date_list[0], end_date_list[1], end_date_list[2])

    formatted_start_date = start.strftime("%Y%m%d")
    formatted_end_date = end.strftime("%Y%m%d")

    for stock in range(0, (len(symbols))):
        data = yf.download(symbols, start = start, end = end)

        col_name_change = {"Close": "close", "High": "high", "Low": "low", "Volume": "volume", "Open": "open", "Adj Close": "adj_close"}
        
        data.rename(columns = col_name_change, inplace = True)
        data["symbol"] = symbols[stock]

        data.to_csv(f"resources/test_{formatted_start_date}-{formatted_end_date}__{symbols[stock]}.csv")
        # tmp = data.iloc[-60:]
        # tmp['close'].plot()

    return data

# Running The Function

In [5]:

symbols = ["BAC", "AAPL"]
# start_date_list = [2013, 1, 1]
start_date_list = [2021, 1, 1]
end_date_list = [2014, 1, 1]

# Run the stock grabber function
stock_grabber(symbols, start_date_list)

[*********************100%***********************]  2 of 2 completed
[*********************100%***********************]  2 of 2 completed

             adj_close                  close                   high  \
                  AAPL        BAC        AAPL        BAC        AAPL
Date
2021-01-04  128.264999  29.319452  129.410004  30.030001  133.610001
2021-01-05  129.850830  29.544008  131.009995  30.260000  131.740005
2021-01-06  125.479851  31.389288  126.599998  32.150002  131.050003
2021-01-07  129.761627  32.082485  130.919998  32.860001  131.630005
2021-01-08  130.881638  31.760296  132.050003  32.529999  132.630005
...                ...        ...         ...        ...         ...
2022-05-12  142.559998  35.070000  142.559998  35.070000  146.199997
2022-05-13  147.110001  35.169998  147.110001  35.169998  148.100006
2022-05-16  145.539993  34.810001  145.539993  34.810001  147.520004
2022-05-17  149.240005  35.990002  149.240005  35.990002  149.770004
2022-05-18  140.820007  34.880001  140.820007  34.880001  147.360001

                              low                   open             \
                  BAC        AAPL        BAC        AAPL        BAC
Date
2021-01-04  30.570000  126.760002  29.750000  133.520004  30.459999
2021-01-05  30.540001  128.429993  29.910000  128.889999  30.170000
2021-01-06  32.619999  126.379997  31.360001  127.720001  31.900000
2021-01-07  33.619999  127.860001  32.840000  128.360001  33.310001
2021-01-08  33.000000  130.229996  32.110001  132.429993  32.919998
...               ...         ...        ...         ...        ...
2022-05-12  35.430000  138.800003  34.259998  142.770004  35.009998
2022-05-13  35.730000  143.110001  34.759998  144.589996  35.529999
2022-05-16  35.169998  144.179993  34.410000  145.550003  35.000000
2022-05-17  36.220001  146.679993  35.430000  148.860001  35.619999
2022-05-18  35.689999  139.899994  34.599998  146.850006  35.619999

               volume            symbol
                 AAPL        BAC
Date
2021-01-04  143301900   51483900   AAPL
2021-01-05   97664900   48507000   AAPL
2021-01-06  155088000  107002800   AAPL
2021-01-07  109578200   74358500   AAPL
2021-01-08  105158200   44641400   AAPL
...               ...        ...    ...
2022-05-12  182602000   61231500   AAPL
2022-05-13  113787000   49069300   AAPL
2022-05-16   86643800   39076500   AAPL
2022-05-17   78336300   42635600   AAPL
2022-05-18  109742900   47396900   AAPL

[347 rows x 13 columns]